### ISSUE TITLE
Apache Camel version is really old in the plugin: 2.24.1! Any maintainer here? Any support for new contributors like me?

### ISSUE THREAD

**Issue by Skrrytch** [hawtio/hawtio-integration#131]
**Hi everyone.** I tried to checkout hawt-integration branch to make some improvements in Apache Camel plugin... but I failed quite early. Even running "yarn start" reports an error:  Couldn't find a script named "start".

After a closer look to **Camel version** in `vendor/pom.xml` I was really surprised that the Camel version there was **2.24.1**.
**Current Apache Camel version is 3.15.0!!!!**

For me that is a show stopper: I do not want to bother with all those possible migration problems when updating to 3.15.0.
I am also a bit lost with node/node-gyp/yarn toolset since I am a Java developer and quite familiar with Typescript/Angular.

Is there anyone who can support me or upgrade to current Apache Camel version?
_Maybe this the wrong place: Is plugin delopment going on elsewhere and this place is just an archive?_ 

I am really interested to contribute with some improvements but need the following support:
- Make it compile/run lokally 
- Understand how to integrate with hawtio main project

I forked both github projects "hawtio" and "hawtio-integration" but I am lost how to make is fly ...

With kind regards.
Bert

By the way: I think that the hawtio camel plugin does not support "Apache Camel 3.15.x" anymore:
Debugging camel routes isn't possible when using 3.15 but works unless I use any version prior to 3.15.0 (e.g. 3.14.1)!

**Comment by tadayosi** [comment]
Hi, thanks for your reporting.

Yes, the Camel version has been intentionally fixed to older 2.x versions because Hawtio is _a Red Hat project_ and the main Red Hat product still uses the Camel 2.x line. That said, I agree that the upstream community is very important and we should keep up with the latest Camel releases as soon as possible.

To upgrade Camel, we need to:
- Upgrade Camel version (https://github.com/hawtio/hawtio-integration#upgrade-apache-camel)
- Split a branch that fixes Camel version to 2.x for the Red Hat product
- Make sure the productisation process use the branched hawtio-integration

BTW, it's weird that you got error when running `yarn start`. Please make sure you installed yarn v1 as the project uses v1. Also make sure to run `yarn install` first before `yarn start`.

**Comment by tadayosi** [comment]
Talking about which version of Camel to support, I think it's most sensible that we only support the latest Camel LTS version. Now it is 3.14.2.
https://camel.apache.org/download/

**Comment by tadayosi** [comment]
About contribution. You can build Hawtio by cloning this repo and run `mvn clean install` in the project:
https://github.com/hawtio/hawtio
Where the Hawtio JS components are tied together is here. The hawtio-console-assembly sub project is built during `mvn clean install` on the hawtio project.
https://github.com/hawtio/hawtio/blob/main/hawtio-console-assembly/app/package.json
