### ISSUE TITLE
Add new icons for new EIPs when upgrading to Apache Camel 2.21

### ISSUE THREAD

**Issue by alexkieling** [hawtio/hawtio-integration#53]
This new release has 2 new EIPs:
- Claim Check
- Saga

We should add specialized icons for those EIPs. There is some code somewhere where these Camel EIPs are mapped to icons, and if there is no mapping then a general icon is used. But the Claim Check EIP should use the icon of "Content Enricher" as it resembles this icon. And Saga should be the icon of a transaction.

**Comment by tadayosi** [comment]
By the way, the current Camel model is very old (2.18.1). It should be upgraded soon.
https://github.com/hawtio/hawtio-integration/blob/v3.2.16/vendor/apache-camel/camelModel.js

**Comment by jamesnetherton** [comment]
We should be able to sync the camel 2.21.0 model from the V1 master branch now.

**Comment by alexkieling** [comment]
@jamesnetherton Are you talking about this file?
https://github.com/hawtio/hawtio/blob/1.x/hawtio-web/src/main/webapp/lib/camelModel.js

It would be great if Camel could provide JS files via npm, right?

**Comment by jamesnetherton** [comment]
@alexkieling Yes that's the one. It gets generated with a Maven plugin:

https://github.com/hawtio/hawtio/blob/1.x/hawtio-json-schema-generator/hawtio-json-schema-generator-plugin/src/main/java/io/hawt/jsonschema/maven/plugin/CamelModelGeneratorMojo.java

If Camel provided the JS for us, it'd be nice. Otherwise we could maybe reimplement the Maven plugin in JS and run it as a gulp task whenever we need to regenerate the Camel model.

**Comment by alexkieling** [comment]
@jamesnetherton hawtio/hawtio master currently depends on camel version 2.21.2. Shall we generate camelModel.js again or using version 2.21.1 is good enough?
https://github.com/hawtio/hawtio/blob/58b31de0a43006233c15975c19ea5d7aed6312da/pom.xml#L59
