### ISSUE TITLE
Add Filtering for camel routes

### ISSUE THREAD

**Issue by Dragas** [hawtio/hawtio-integration#90]
Hi!

I've got a context which contains about 400 routes in it and any action seems to stall the UI. I've tried using the search feature, but it does not filter the provided routes, instead only highlights them. How do you filter them instead?

**Comment by alexkieling** [comment]
There is no way to filter the tree but it's a good improvement. I'll have a look at it.

**Comment by alexkieling** [comment]
@Dragas it think filtering out unmatched nodes won't be an easy improvement due to the logic being encapsulated in a third-party Tree component.
Tree search documentation: https://github.com/patternfly/patternfly-bootstrap-treeview#searchpattern-options

**Comment by Dragas** [comment]
Hmm, reading through it I see that it emits a `searchComplete` event, which has a second argument of results. Does the tree component support changing the data set while search is being done?

**Comment by alexkieling** [comment]
@astefanutti One solution would be emitting an event with the search results from [here](https://github.com/hawtio/hawtio-integration/blob/701e525527d5d678df79e51ee26f592999b6e58b/plugins/jmx/ts/tree/tree-header.controller.ts#L38) to [here](https://github.com/hawtio/hawtio-integration/blob/701e525527d5d678df79e51ee26f592999b6e58b/plugins/jmx/ts/tree/tree.component.ts#L20) and invoking a modified version of populateTree that takes an array of nodes. When the list of results is empty, it populates the tree with `this.workspace.tree.children`. Deleting characters doesn't show correct results because the search is done on the visible tree and only when all characters are deleted we can populate the tree with all nodes. I've played with it and the UX isn't terrible.
What do you think?

**Comment by ostrovskyde** [comment]
@astefanutti is there a chance to implement filtering?
As for now the search feature is quite useless and painful for the large trees. It is required to manually scroll down and look up for the highlighted items or "ctrl + f5" to search for the search results...

I'm pretty happy with your above suggestion. Could we move forward and implement it? Thanks.
