### ISSUE TITLE
Feature Request - Spring boot info

### ISSUE THREAD

**Issue by choss** [hawtio/hawtio-integration#99]
Similarly to the "Health" tab for spring boot applications, could we also have the "info" endpoint/MBean integrated into hawt-io?

I think the cards for health with the details are great and show exactly what we need. 

I'd like to help, but I have no angular skills

**Comment by rfelgent** [comment]
Hi @tadayosi ,

do you think that this feature request is worth the time to invest ? The reason why I ask is, that the post is from March 2020...  

I would use the "health" code as template for creating the "info" code.

Best regards

**Comment by tadayosi** [comment]
Yes, contributions are always welcome.

**Comment by rfelgent** [comment]
Hi @tadayosi ,

I had some trouble to setup the local build environment on my win10 OS due to some version library conflicts (e.g.: python2 <=> python3, node12 <=> node8, gulp and so on). In the end, I used a dedicated dockerfile for compiling and running the project.

Do you think it might be a good idea to provide a Dockerfile having all libs/dependencies required to build/compile/run the project ? Other committers might benefit from such a Dockerfile, too.

If you agree, I would recommend to create another MR request and another issue before continuing with this issue. What do you think?

**Comment by tadayosi** [comment]
I'd normally just use tools like pyenv and nvm to workaround such version problems (FYI I use Linux). Doesn't that work for you?
I haven't heard from any other contributors that they have such difficulty so far (and I don't either).
